<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">enableInterception</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQoJU3RyaW5nCSRyZXNvdXJjZUlEID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxp
bmVDdXJzb3IsICJlbmFibGVkIiApOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQpib29s
ZWFuIGVuYWJsZWQ7DQppZiAoJHJlc291cmNlSUQgPT0gbnVsbCB8fCAkcmVzb3VyY2VJRC5sZW5n
dGgoKSA9PSAwKSB7DQoJZW5hYmxlZCA9IEFPUENoYWluUHJvY2Vzc29yLmdldEluc3RhbmNlKCku
aXNFbmFibGVkKCk7DQp9IGVsc2Ugew0KCWVuYWJsZWQgPSBCb29sZWFuLnZhbHVlT2YoJHJlc291
cmNlSUQpOw0KCUFPUENoYWluUHJvY2Vzc29yLmdldEluc3RhbmNlKCkuc2V0RW5hYmxlZChlbmFi
bGVkKTsNCn0NCg0KLy8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBw
aXBlbGluZS5nZXRDdXJzb3IoKTsNCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJl
bmFibGVkIiwgQm9vbGVhbi50b1N0cmluZyhlbmFibGVkKSApOw0KcGlwZWxpbmVDdXJzb3JfMS5k
ZXN0cm95KCk7DQoJ</value>
</Values>
