<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">restorePipelineFromIData</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCk9iamVj
dCBwaXBlbGluZVhtbCA9IElEYXRhVXRpbC5nZXQoIHBpcGVsaW5lQ3Vyc29yLCAicGlwZWxpbmVY
bWwiICk7DQpJbnB1dFN0cmVhbSBpczsNCnRyeSB7DQoJaWYgKHBpcGVsaW5lWG1sIGluc3RhbmNl
b2YgRG9jdW1lbnQpIHsNCgkJSURhdGFVdGlsLm1lcmdlKG5ldyBJRGF0YVhNTENvZGVyKCkuZGVj
b2RlKChEb2N1bWVudClwaXBlbGluZVhtbCksIHBpcGVsaW5lKTsNCgl9IGVsc2Ugew0KCQlpZiAo
cGlwZWxpbmVYbWwgaW5zdGFuY2VvZiBJbnB1dFN0cmVhbSkgew0KCQkJaXMgPSAoSW5wdXRTdHJl
YW0pIHBpcGVsaW5lWG1sOw0KCQl9IGVsc2UgaWYgKHBpcGVsaW5lWG1sIGluc3RhbmNlb2YgU3Ry
aW5nKSB7DQoJCQlpcyA9IG5ldyBCeXRlQXJyYXlJbnB1dFN0cmVhbSgoKFN0cmluZylwaXBlbGlu
ZVhtbCkuZ2V0Qnl0ZXMoKSk7DQoJCX0gZWxzZSB7DQoJCQl0aHJvdyBuZXcgU2VydmljZUV4Y2Vw
dGlvbigiVW5rbm93biB0eXBlICIgKyBwaXBlbGluZVhtbC5nZXRDbGFzcygpKTsNCgkJfQ0KCQlp
ZiAoaXMuYXZhaWxhYmxlKCkgPiAwKSB7DQoJCQlYTUxDb2RlcldyYXBwZXIgeGMgPSBuZXcgWE1M
Q29kZXJXcmFwcGVyKCk7DQoJCQlJRGF0YVV0aWwubWVyZ2UoeGMuZGVjb2RlKGlzKSwgcGlwZWxp
bmUpOw0KCQl9DQoJfQ0KfSBjYXRjaCAoSU9FeGNlcHRpb24gZSkgew0KCXRocm93IG5ldyBTZXJ2
aWNlRXhjZXB0aW9uKGUpOw0KfSBmaW5hbGx5IHsNCglwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7
DQp9CQkNCgk=</value>
</Values>
